### ISSUE TITLE
UI errors with inconsistent controls table

### ISSUE THREAD

**Issue by AMGarkin** [sirinsidiator/ESO-LibAddonMenu#15] opened 2015-02-25 12:57 UTC
Recent version of LAM uses:

```lua
    for sIndex=1,#widgetData.controls do
        subWidgetData = widgetData.controls[sIndex]
        subWidgetType = subWidgetData.type
```
instead of:
```lua
    for _, subWidgetData in ipairs(widgetData.controls) do
        local subWidgetType = subWidgetData.type
```

Due to this change, controls table with invalid indexes throws UI errors:
```
2015-02-25T13:36:10.017+01:00 |cff0000Lua Error: user:/AddOns/AwesomeGuildStore/lib/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:129: attempt to index a nil value
stack traceback:
	user:/AddOns/AwesomeGuildStore/lib/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:129: in function 'CreateOptionsControls'
	user:/AddOns/AwesomeGuildStore/lib/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:187: in function 'ToggleAddonPanels'
	[C]: in function 'SetHidden'
	user:/AddOns/AwesomeGuildStore/lib/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:306: in function '(anonymous)'|r
```

As there is no real reason for this change in code, I recommend reverting it back to ipairs.

See comments in here:
http://www.esoui.com/downloads/fileinfo.php?id=605#comments

**Comment by sirinsidiator** [comment] 2015-02-25 13:16
I think it might be a better idea to validate the table structure and show a warning so that an author sees that something is wrong with his settings panel.
Just reverting it will help with the symptoms but won't fix the root cause of the error.

**Comment by merlight** [comment] 2015-02-26 14:26
Well if you have holes in that table, you using ipairs you will see (or rather not see) the controls beyond that hole are missing ;)

**Closed** 2015-03-07 09:23 UTC
Labels: bug
